ERROR | 2022-06-28 17:09:39,029 | main.py:40 | BOT WAS STARTED
NoneType: None
WARNING | 2022-06-28 17:10:59,732 | executor.py:329 | Goodbye!
